#!/usr/bin/env python
"""Write and validate a deterministic manifest for RePromptTax paper artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ARTIFACT_PATHS = [
    "README.md",
    "additional_experiments_plan .md",
    "reprompt_tax_workshop_paper_plan.md",
    "data/benchmark_stress_v0.1.jsonl",
    "data/benchmark_stress_v0.2.jsonl",
    "data/benchmark_stress_v0.3_expansion.jsonl",
    "data/coverage_native_review_v03/coverage_native_review_launch_checklist_v03.md",
    "data/coverage_native_review_v03/coverage_native_review_manifest_v03.md",
    "data/coverage_native_review_v03/coverage_native_review_packet_v03.csv",
    "data/coverage_native_review_v03/coverage_native_review_roster_template_v03.csv",
    "data/coverage_native_review_v03/review_sheets_v03/README.md",
    "data/coverage_native_review_v03/review_sheets_v03/coverage_native_review_sheet_v03_arabic_instruction_arabic_filenames.html",
    "data/coverage_native_review_v03/review_sheets_v03/coverage_native_review_sheet_v03_english_instruction_arabic_content.html",
    "data/coverage_native_review_v03/review_sheets_v03/coverage_native_review_sheet_v03_english_instruction_hindi_content.html",
    "data/coverage_native_review_v03/review_sheets_v03/coverage_native_review_sheet_v03_english_instruction_spanish_content.html",
    "data/coverage_native_review_v03/review_sheets_v03/coverage_native_review_sheet_v03_hindi_english_instruction_hindi_devanagari.html",
    "data/coverage_native_review_v03/review_sheets_v03/coverage_native_review_sheet_v03_spanish_instruction_arabic_quote.html",
    "data/coverage_native_review_v03/review_sheets_v03/index.html",
    "data/coverage_native_review_v03/coverage_native_review_v03_arabic_instruction_arabic_filenames.csv",
    "data/coverage_native_review_v03/coverage_native_review_v03_english_instruction_arabic_content.csv",
    "data/coverage_native_review_v03/coverage_native_review_v03_english_instruction_hindi_content.csv",
    "data/coverage_native_review_v03/coverage_native_review_v03_english_instruction_spanish_content.csv",
    "data/coverage_native_review_v03/coverage_native_review_v03_hindi_english_instruction_hindi_devanagari.csv",
    "data/coverage_native_review_v03/coverage_native_review_v03_spanish_instruction_arabic_quote.csv",
    "data/stress_v03_smoke6_ids.txt",
    "data/stress_v03_pilot24_ids.txt",
    "data/stress_v03_pilot24_remaining18_ids.txt",
    "data/stress_v02_gpt55_pilot40_ids.txt",
    "data/stress_v02_new_60_ids.txt",
    "data/stress_v02_new_balanced_24_ids.txt",
    "data/stress_v02_remaining_36_ids.txt",
    "data/human_audit/audit_manifest_v0.2.md",
    "data/human_audit/human_audit_answer_key_v0.2.csv",
    "data/human_audit/human_audit_annotator_roster_template_v0.2.csv",
    "data/human_audit/human_audit_launch_checklist_v0.2.md",
    "data/human_audit/human_audit_packet_v0.2.csv",
    "data/human_audit/human_audit_packet_v0.2_ar-en.csv",
    "data/human_audit/human_audit_packet_v0.2_es-en.csv",
    "data/human_audit/human_audit_packet_v0.2_hi-en.csv",
    "data/human_audit/review_sheets_v0.2/README.md",
    "data/human_audit/review_sheets_v0.2/human_audit_review_sheet_v0.2_ar-en.html",
    "data/human_audit/review_sheets_v0.2/human_audit_review_sheet_v0.2_es-en.html",
    "data/human_audit/review_sheets_v0.2/human_audit_review_sheet_v0.2_hi-en.html",
    "data/human_audit/review_sheets_v0.2/index.html",
    "data/current_model_human_audit/audit_manifest_v0.2_current_gpt5.md",
    "data/current_model_human_audit/human_audit_answer_key_v0.2_current_gpt5.csv",
    "data/current_model_human_audit/human_audit_annotator_roster_template_v0.2_current_gpt5.csv",
    "data/current_model_human_audit/human_audit_launch_checklist_v0.2_current_gpt5.md",
    "data/current_model_human_audit/human_audit_packet_v0.2_current_gpt5.csv",
    "data/current_model_human_audit/human_audit_packet_v0.2_current_gpt5_ar-en.csv",
    "data/current_model_human_audit/human_audit_packet_v0.2_current_gpt5_es-en.csv",
    "data/current_model_human_audit/human_audit_packet_v0.2_current_gpt5_hi-en.csv",
    "data/current_model_human_audit/review_sheets_v0.2_current_gpt5/README.md",
    "data/current_model_human_audit/review_sheets_v0.2_current_gpt5/human_audit_review_sheet_v0.2_current_gpt5_ar-en.html",
    "data/current_model_human_audit/review_sheets_v0.2_current_gpt5/human_audit_review_sheet_v0.2_current_gpt5_es-en.html",
    "data/current_model_human_audit/review_sheets_v0.2_current_gpt5/human_audit_review_sheet_v0.2_current_gpt5_hi-en.html",
    "data/current_model_human_audit/review_sheets_v0.2_current_gpt5/index.html",
    "docs/benchmark_card.md",
    "docs/evaluation_card.md",
    "docs/human_audit_guide.md",
    "docs/result_card.md",
    "paper/appendix.md",
    "paper/all_model_paired_significance_v02.md",
    "paper/all_model_uncertainty_v02.md",
    "paper/benchmark_quality_audit_v02.md",
    "paper/claim_evidence_checklist.md",
    "paper/component_breakdown_v02_full120.md",
    "paper/coverage_expansion_v03.md",
    "paper/coverage_native_review_design_v03.md",
    "paper/coverage_pilot_gpt54mini_v03.md",
    "paper/coverage_smoke_gpt55_v03.md",
    "paper/coverage_smoke_gpt54mini_v03.md",
    "paper/current_model_case_studies_v02.md",
    "paper/current_model_error_analysis_v02.md",
    "paper/current_model_heterogeneity_v02.md",
    "paper/current_model_regression_risk_v02.md",
    "paper/current_model_human_audit_design_v02.md",
    "paper/current_model_refresh_v02.md",
    "paper/current_model_uncertainty_v02.md",
    "paper/current_model_scorer_sensitivity_v02.md",
    "paper/current_prompt_mechanism_gpt54mini_v02.md",
    "paper/current_prompt_mechanism_gpt55_v02.md",
    "paper/contract_benefit_decomposition_v02.md",
    "paper/prompt_family_scorecard_v02.md",
    "paper/completed_label_claim_gates_v02.md",
    "paper/discovery_cue_analysis.md",
    "paper/discovery_snapshot.md",
    "paper/error_atlas_v02_full120.md",
    "paper/experiment_ledger_v02.md",
    "paper/followup_plan_readiness_v02.md",
    "paper/generation_progress_probe_v02.md",
    "paper/efficiency_tradeoff_v02.md",
    "paper/extended_abstract_draft.md",
    "paper/failure_mode_analysis_v02_full120.md",
    "paper/human_audit_design_audit_v02.md",
    "paper/human_audit_acceptance_rules_v02.md",
    "paper/human_audit_completion_plan.md",
    "paper/human_audit_threshold_rationale_v02.md",
    "paper/item_consistency_analysis_v02_full120.md",
    "paper/judge_agreement_analysis_v02_full120.md",
    "paper/judge_refresh_gpt55_v02_full120.md",
    "paper/language_slice_analysis_v02_full120.md",
    "paper/label_collection_dispatch_v02.md",
    "paper/label_collection_launch_pack_v02.md",
    "paper/figures/ftga_by_condition.png",
    "paper/figures/repair_curve.png",
    "paper/main.pdf",
    "paper/main.tex",
    "paper/paired_significance_gpt54mini_v02_full120.md",
    "paper/paired_significance_gpt55_v02_full120.md",
    "paper/paired_significance_gpt55_v02_pilot40.md",
    "paper/paired_significance_v02_full120.md",
    "paper/prompt_control_analysis.md",
    "paper/prompt_ablation_analysis.md",
    "paper/qualitative_examples.md",
    "paper/related_work_positioning_v02.md",
    "paper/refs.bib",
    "paper/repair_realism_editing_baseline24.md",
    "paper/repair_dynamics_v02_full120.md",
    "paper/results_snapshot.md",
    "paper/scorer_ablation_sensitivity_v02_full120.md",
    "paper/sections/00_abstract.tex",
    "paper/sections/01_introduction.tex",
    "paper/sections/02_interaction_contracts_and_metrics.tex",
    "paper/sections/03_benchmark_construction.tex",
    "paper/sections/04_experimental_protocol.tex",
    "paper/sections/05_results.tex",
    "paper/sections/06_discussion.tex",
    "paper/sections/07_related_work.tex",
    "paper/sections/08_limitations_and_ethics.tex",
    "paper/sections/09_conclusion.tex",
    "paper/task_useful_failure_analysis_gpt54mini_v02_full120.md",
    "paper/task_useful_failure_analysis_gpt55_v02_full120.md",
    "paper/task_useful_failure_analysis_gpt55_v02_pilot40.md",
    "paper/task_useful_failure_analysis_v02_full120.md",
    "paper/token_burden_analysis_v02_full120.md",
    "prompts/baseline_system.txt",
    "prompts/content_preservation_system.txt",
    "prompts/generic_helpfulness_system.txt",
    "prompts/global_interaction_contract.txt",
    "prompts/judge_prompt.txt",
    "results/discovery/wildchat_20k_repair_cues/category_counts.csv",
    "results/discovery/wildchat_20k_repair_cues/cue_category_conversation_counts.csv",
    "results/discovery/wildchat_20k_repair_cues/cue_discovery_overview.csv",
    "results/discovery/wildchat_20k_repair_cues/cue_language_category_counts.csv",
    "results/discovery/wildchat_20k_repair_cues/cue_pattern_counts.csv",
    "results/discovery/wildchat_20k_repair_cues/hit_metadata_hashed.csv",
    "results/discovery/wildchat_20k_repair_cues/repeated_cue_conversations_hashed.csv",
    "results/discovery/wildchat_20k_repair_cues/summary.json",
    "results/figures/openai_three_model_stress_v02_full120/ftga_by_condition.png",
    "results/figures/openai_three_model_stress_v02_full120/ftga_by_condition_source.csv",
    "results/figures/openai_three_model_stress_v02_full120/repair_curve.png",
    "results/figures/openai_three_model_stress_v02_full120/repair_curve_source.csv",
    "results/tables/benchmark_quality_v02/benchmark_quality_by_family.csv",
    "results/tables/benchmark_quality_v02/benchmark_quality_by_language.csv",
    "results/tables/benchmark_quality_v02/benchmark_quality_by_language_family.csv",
    "results/tables/benchmark_quality_v02/benchmark_quality_summary.csv",
    "results/tables/coverage_expansion_v03/coverage_expansion_by_content_language.csv",
    "results/tables/coverage_expansion_v03/coverage_expansion_by_slice.csv",
    "results/tables/coverage_expansion_v03/coverage_expansion_privacy_scan.csv",
    "results/tables/coverage_expansion_v03/coverage_expansion_summary.csv",
    "results/tables/coverage_native_review_v03_design/coverage_native_review_by_content_language.csv",
    "results/tables/coverage_native_review_v03_design/coverage_native_review_by_instruction_language.csv",
    "results/tables/coverage_native_review_v03_design/coverage_native_review_by_language_pair.csv",
    "results/tables/coverage_native_review_v03_design/coverage_native_review_by_slice.csv",
    "results/tables/coverage_native_review_v03_design/coverage_native_review_summary.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/coverage_smoke_by_slice.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/coverage_smoke_first_turn_failures.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/coverage_smoke_summary.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/failure_types_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/metrics_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/metrics_by_language.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/metrics_summary.csv",
    "results/tables/openai_gpt54mini_stress_v03_smoke6/trajectory_metrics.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/coverage_pilot_by_slice.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/coverage_pilot_first_turn_failures.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/coverage_pilot_paired_items.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/coverage_pilot_summary.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/failure_types_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/metrics_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/metrics_by_language.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/metrics_summary.csv",
    "results/tables/openai_gpt54mini_stress_v03_pilot24/trajectory_metrics.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/coverage_smoke_by_slice.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/coverage_smoke_first_turn_failures.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/coverage_smoke_summary.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/failure_types_by_family.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/metrics_by_family.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/metrics_by_language.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/metrics_summary.csv",
    "results/tables/openai_gpt55_stress_v03_smoke6/trajectory_metrics.csv",
    "results/model_outputs/openai_gpt54mini_stress_v02_full120.jsonl",
    "results/model_outputs/openai_gpt54mini_stress_v02_full120_content_preservation.jsonl",
    "results/model_outputs/openai_gpt54mini_stress_v03_pilot24.jsonl",
    "results/model_outputs/openai_gpt54mini_stress_v03_pilot24_remaining18.jsonl",
    "results/model_outputs/openai_gpt54mini_stress_v03_smoke6.jsonl",
    "results/model_outputs/openai_gpt55_stress_v02_full120.jsonl",
    "results/model_outputs/openai_gpt55_stress_v02_full120_content_preservation.jsonl",
    "results/model_outputs/openai_gpt55_stress_v02_pilot40.jsonl",
    "results/model_outputs/openai_gpt55_stress_v03_smoke6.jsonl",
    "results/tables/current_model_refresh_v02/current_model_refresh_api_usage.csv",
    "results/tables/current_model_refresh_v02/current_model_refresh_summary.csv",
    "results/tables/current_model_uncertainty_v02/current_model_uncertainty.csv",
    "results/tables/current_model_case_studies_v02/current_model_case_studies.csv",
    "results/tables/current_model_error_analysis_v02/current_model_contract_residual_cases.csv",
    "results/tables/current_model_error_analysis_v02/current_model_error_by_family.csv",
    "results/tables/current_model_error_analysis_v02/current_model_error_by_language.csv",
    "results/tables/current_model_error_analysis_v02/current_model_error_summary.csv",
    "results/tables/current_model_error_analysis_v02/current_model_first_turn_failures.csv",
    "results/tables/current_model_error_analysis_v02/current_model_paired_transitions.csv",
    "results/tables/current_model_heterogeneity_v02/current_model_heterogeneity_by_stratum.csv",
    "results/tables/current_model_heterogeneity_v02/current_model_heterogeneity_leave_one.csv",
    "results/tables/current_model_regression_risk_v02/current_model_contract_regression_cases.csv",
    "results/tables/current_model_regression_risk_v02/current_model_regression_risk_summary.csv",
    "results/tables/current_model_regression_risk_v02/current_model_resolved_to_unresolved_cases.csv",
    "results/tables/current_model_scorer_sensitivity_v02/current_model_scorer_sensitivity_by_condition.csv",
    "results/tables/current_model_scorer_sensitivity_v02/current_model_scorer_sensitivity_by_model_condition.csv",
    "results/tables/current_model_scorer_sensitivity_v02/current_model_scorer_sensitivity_by_model_family_condition.csv",
    "results/tables/current_model_scorer_sensitivity_v02/current_model_scorer_sensitivity_failure_signatures.csv",
    "results/tables/current_model_scorer_sensitivity_v02/current_model_scorer_sensitivity_top_failure_signatures.csv",
    "results/tables/current_prompt_mechanism_gpt54mini_v02/current_prompt_mechanism_api_usage.csv",
    "results/tables/current_prompt_mechanism_gpt54mini_v02/current_prompt_mechanism_by_family.csv",
    "results/tables/current_prompt_mechanism_gpt54mini_v02/current_prompt_mechanism_paired_effects.csv",
    "results/tables/current_prompt_mechanism_gpt54mini_v02/current_prompt_mechanism_summary.csv",
    "results/tables/current_prompt_mechanism_gpt55_v02/current_prompt_mechanism_api_usage.csv",
    "results/tables/current_prompt_mechanism_gpt55_v02/current_prompt_mechanism_by_family.csv",
    "results/tables/current_prompt_mechanism_gpt55_v02/current_prompt_mechanism_paired_effects.csv",
    "results/tables/current_prompt_mechanism_gpt55_v02/current_prompt_mechanism_summary.csv",
    "results/tables/prompt_family_scorecard_v02/prompt_family_by_family.csv",
    "results/tables/prompt_family_scorecard_v02/prompt_family_model_scorecard.csv",
    "results/tables/prompt_family_scorecard_v02/prompt_family_paired_comparisons.csv",
    "results/tables/prompt_family_scorecard_v02/prompt_family_summary.csv",
    "results/tables/all_model_paired_significance_v02/all_model_paired_significance.csv",
    "results/tables/all_model_uncertainty_v02/all_model_cluster_bootstrap.csv",
    "results/tables/contract_benefit_decomposition_v02/contract_benefit_by_family.csv",
    "results/tables/contract_benefit_decomposition_v02/contract_benefit_by_generation.csv",
    "results/tables/contract_benefit_decomposition_v02/contract_benefit_by_generation_family.csv",
    "results/tables/contract_benefit_decomposition_v02/contract_benefit_by_language.csv",
    "results/tables/contract_benefit_decomposition_v02/contract_benefit_overall.csv",
    "results/tables/generation_progress_probe_v02/generation_progress_by_family.csv",
    "results/tables/generation_progress_probe_v02/generation_progress_categories.csv",
    "results/tables/generation_progress_probe_v02/generation_progress_item_matrix.csv",
    "results/tables/generation_progress_probe_v02/generation_progress_summary.csv",
    "results/tables/human_audit_acceptance_rules_v02/human_audit_acceptance_rules.csv",
    "results/tables/human_audit_threshold_rationale_v02/human_audit_threshold_rationale.csv",
    "results/tables/completed_label_claim_gates_v02/completed_label_claim_gates.csv",
    "results/tables/label_collection_launch_pack_v02/label_collection_commands.csv",
    "results/tables/label_collection_launch_pack_v02/label_collection_files.csv",
    "results/tables/label_collection_launch_pack_v02/label_collection_surfaces.csv",
    "results/tables/label_collection_dispatch_v02/label_collection_dispatch_manifest.csv",
    "results/tables/label_collection_dispatch_v02/label_collection_dispatch_summary.csv",
    "results/label_collection_bundles_v02/label_collection_bundle_manifest.csv",
    "results/label_collection_bundles_v02/label_collection_bundles.md",
    "results/label_collection_bundles_v02/human_audit_v02/ar-en.zip",
    "results/label_collection_bundles_v02/human_audit_v02/es-en.zip",
    "results/label_collection_bundles_v02/human_audit_v02/hi-en.zip",
    "results/label_collection_bundles_v02/current_model_human_audit_v02/ar-en.zip",
    "results/label_collection_bundles_v02/current_model_human_audit_v02/es-en.zip",
    "results/label_collection_bundles_v02/current_model_human_audit_v02/hi-en.zip",
    "results/label_collection_bundles_v02/coverage_native_review_v03/arabic_instruction_arabic_filenames.zip",
    "results/label_collection_bundles_v02/coverage_native_review_v03/english_instruction_arabic_content.zip",
    "results/label_collection_bundles_v02/coverage_native_review_v03/english_instruction_hindi_content.zip",
    "results/label_collection_bundles_v02/coverage_native_review_v03/english_instruction_spanish_content.zip",
    "results/label_collection_bundles_v02/coverage_native_review_v03/hindi_english_instruction_hindi_devanagari.zip",
    "results/label_collection_bundles_v02/coverage_native_review_v03/spanish_instruction_arabic_quote.zip",
    "results/tables/efficiency_tradeoff_v02/efficiency_tradeoff_by_model_condition.csv",
    "results/tables/efficiency_tradeoff_v02/efficiency_tradeoff_paired_effects.csv",
    "results/tables/efficiency_tradeoff_v02/efficiency_tradeoff_trajectory_metrics.csv",
    "results/tables/followup_plan_readiness_v02/followup_plan_readiness.csv",
    "results/tables/experiment_ledger_v02/api_usage_by_artifact.csv",
    "results/tables/experiment_ledger_v02/api_usage_by_judge.csv",
    "results/tables/experiment_ledger_v02/api_usage_by_model_condition.csv",
    "results/tables/experiment_ledger_v02/api_usage_by_repair_variant.csv",
    "results/tables/experiment_ledger_v02/experiment_ledger_summary.csv",
    "results/tables/human_audit_v0.2_design/human_audit_design_by_auto_failure_type.csv",
    "results/tables/human_audit_v0.2_design/human_audit_design_by_family.csv",
    "results/tables/human_audit_v0.2_design/human_audit_design_by_language.csv",
    "results/tables/human_audit_v0.2_design/human_audit_design_by_language_family.csv",
    "results/tables/human_audit_v0.2_design/human_audit_design_by_model_condition.csv",
    "results/tables/human_audit_v0.2_design/human_audit_design_summary.csv",
    "results/tables/current_model_human_audit_v02_design/human_audit_design_by_auto_failure_type.csv",
    "results/tables/current_model_human_audit_v02_design/human_audit_design_by_family.csv",
    "results/tables/current_model_human_audit_v02_design/human_audit_design_by_language.csv",
    "results/tables/current_model_human_audit_v02_design/human_audit_design_by_language_family.csv",
    "results/tables/current_model_human_audit_v02_design/human_audit_design_by_model_condition.csv",
    "results/tables/current_model_human_audit_v02_design/human_audit_design_summary.csv",
    "results/scores/openai_gpt54mini_stress_v02_full120_auto_scores.jsonl",
    "results/scores/openai_gpt54mini_stress_v02_full120_content_preservation_auto_scores.jsonl",
    "results/scores/openai_gpt54mini_stress_v03_pilot24_auto_scores.jsonl",
    "results/scores/openai_gpt54mini_stress_v03_smoke6_auto_scores.jsonl",
    "results/scores/openai_gpt55_stress_v02_full120_auto_scores.jsonl",
    "results/scores/openai_gpt55_stress_v02_full120_content_preservation_auto_scores.jsonl",
    "results/scores/openai_gpt55_stress_v02_pilot40_auto_scores.jsonl",
    "results/scores/openai_gpt55_stress_v03_smoke6_auto_scores.jsonl",
    "results/scores/openai_mini_gpt41_stress_v02_remaining36_auto_scores.jsonl",
    "results/scores/openai_nano_stress60_generic_helpfulness_auto_scores.jsonl",
    "results/scores/openai_nano_stress_v02_full120_content_preservation_auto_scores.jsonl",
    "results/scores/openai_nano_stress_v02_full120_generic_helpfulness_auto_scores.jsonl",
    "results/scores/openai_nano_stress_v02_new60_generic_helpfulness_auto_scores.jsonl",
    "results/scores/openai_nano_stress_v02_remaining36_auto_scores.jsonl",
    "results/scores/openai_three_model_stress_v02_repair_realism_editing_baseline24.jsonl",
    "results/scores/openai_three_model_stress60_auto_scores.jsonl",
    "results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl",
    "results/scores/openai_three_model_stress_v02_full120_judge_audit72.jsonl",
    "results/scores/openai_three_model_stress_v02_full120_judge_gpt55_audit72.jsonl",
    "results/scores/openai_three_model_stress_v02_new24_auto_scores.jsonl",
    "results/tables/openai_nano_stress_v02_full120_generic_helpfulness/failure_types_by_family.csv",
    "results/tables/openai_nano_stress_v02_full120_generic_helpfulness/metrics_by_family.csv",
    "results/tables/openai_nano_stress_v02_full120_generic_helpfulness/metrics_by_language.csv",
    "results/tables/openai_nano_stress_v02_full120_generic_helpfulness/metrics_summary.csv",
    "results/tables/openai_nano_stress_v02_full120_generic_helpfulness/trajectory_metrics.csv",
    "results/tables/openai_nano_stress_v02_full120_content_preservation/failure_types_by_family.csv",
    "results/tables/openai_nano_stress_v02_full120_content_preservation/metrics_by_family.csv",
    "results/tables/openai_nano_stress_v02_full120_content_preservation/metrics_by_language.csv",
    "results/tables/openai_nano_stress_v02_full120_content_preservation/metrics_summary.csv",
    "results/tables/openai_nano_stress_v02_full120_content_preservation/trajectory_metrics.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/failure_types_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/metrics_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/metrics_by_language.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/metrics_summary.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/paired_contract_effects_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/paired_contract_effects_by_model.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/paired_significance_by_model.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/task_useful_failure_by_condition.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/task_useful_failure_by_family_condition.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/task_useful_failure_by_language_condition.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/task_useful_failure_by_model_condition.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/task_useful_failure_signatures.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120/trajectory_metrics.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120_content_preservation/failure_types_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120_content_preservation/metrics_by_family.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120_content_preservation/metrics_by_language.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120_content_preservation/metrics_summary.csv",
    "results/tables/openai_gpt54mini_stress_v02_full120_content_preservation/trajectory_metrics.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/failure_types_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/metrics_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/metrics_by_language.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/metrics_summary.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/paired_contract_effects_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/paired_contract_effects_by_model.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/paired_significance_by_model.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/task_useful_failure_by_condition.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/task_useful_failure_by_family_condition.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/task_useful_failure_by_language_condition.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/task_useful_failure_by_model_condition.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/task_useful_failure_signatures.csv",
    "results/tables/openai_gpt55_stress_v02_pilot40/trajectory_metrics.csv",
    "results/tables/openai_gpt55_stress_v02_full120/failure_types_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_full120/metrics_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_full120/metrics_by_language.csv",
    "results/tables/openai_gpt55_stress_v02_full120/metrics_summary.csv",
    "results/tables/openai_gpt55_stress_v02_full120/paired_contract_effects_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_full120/paired_contract_effects_by_model.csv",
    "results/tables/openai_gpt55_stress_v02_full120/paired_significance_by_model.csv",
    "results/tables/openai_gpt55_stress_v02_full120/task_useful_failure_by_condition.csv",
    "results/tables/openai_gpt55_stress_v02_full120/task_useful_failure_by_family_condition.csv",
    "results/tables/openai_gpt55_stress_v02_full120/task_useful_failure_by_language_condition.csv",
    "results/tables/openai_gpt55_stress_v02_full120/task_useful_failure_by_model_condition.csv",
    "results/tables/openai_gpt55_stress_v02_full120/task_useful_failure_signatures.csv",
    "results/tables/openai_gpt55_stress_v02_full120/trajectory_metrics.csv",
    "results/tables/openai_gpt55_stress_v02_full120_content_preservation/failure_types_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_full120_content_preservation/metrics_by_family.csv",
    "results/tables/openai_gpt55_stress_v02_full120_content_preservation/metrics_by_language.csv",
    "results/tables/openai_gpt55_stress_v02_full120_content_preservation/metrics_summary.csv",
    "results/tables/openai_gpt55_stress_v02_full120_content_preservation/trajectory_metrics.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_ablation/prompt_ablation_by_family.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_ablation/prompt_ablation_contract_vs_content_by_family.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_ablation/prompt_ablation_contract_vs_content_by_language.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_ablation/prompt_ablation_contract_vs_content_examples.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_ablation/prompt_ablation_contract_vs_content_items.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_ablation/prompt_ablation_paired_effects.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_ablation/prompt_ablation_summary.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_control/prompt_control_paired_effects.csv",
    "results/tables/openai_nano_stress_v02_full120_prompt_control/prompt_control_summary.csv",
    "results/tables/openai_three_model_stress60/trajectory_metrics.csv",
    "results/tables/openai_three_model_stress_v02_full120/failure_type_summary.csv",
    "results/tables/openai_three_model_stress_v02_full120/failure_types_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120/family_effect_summary.csv",
    "results/tables/openai_three_model_stress_v02_full120/component_paired_effects_by_model.csv",
    "results/tables/openai_three_model_stress_v02_full120/component_pass_by_family_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/component_pass_by_language_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/component_pass_by_model_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/first_turn_error_atlas.csv",
    "results/tables/openai_three_model_stress_v02_full120/item_consistency_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120/item_consistency_by_item.csv",
    "results/tables/openai_three_model_stress_v02_full120/item_consistency_hardest_items.csv",
    "results/tables/openai_three_model_stress_v02_full120/item_consistency_summary.csv",
    "results/tables/openai_three_model_stress_v02_full120/language_slice_aggregate_effects.csv",
    "results/tables/openai_three_model_stress_v02_full120/language_slice_metrics.csv",
    "results/tables/openai_three_model_stress_v02_full120/language_slice_paired_effects.csv",
    "results/tables/openai_three_model_stress_v02_full120/metrics_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120/metrics_by_language.csv",
    "results/tables/openai_three_model_stress_v02_full120/metrics_summary.csv",
    "results/tables/openai_three_model_stress_v02_full120/paired_contract_effects_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120/paired_contract_effects_by_model.csv",
    "results/tables/openai_three_model_stress_v02_full120/paired_significance_by_model.csv",
    "results/tables/openai_three_model_stress_v02_full120/repair_dynamics_by_family_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/repair_dynamics_by_language_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/repair_dynamics_by_model_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/repair_paired_effects_by_model.csv",
    "results/tables/openai_three_model_stress_v02_full120/repair_rtt_transition_by_model.csv",
    "results/tables/openai_three_model_stress_v02_full120/scorer_ablation_by_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/scorer_ablation_by_family_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/scorer_ablation_by_model_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/scorer_ablation_failure_signatures.csv",
    "results/tables/openai_three_model_stress_v02_full120/scorer_ablation_top_failure_signatures.csv",
    "results/tables/openai_three_model_stress_v02_full120/task_useful_failure_by_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/task_useful_failure_by_family_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/task_useful_failure_by_language_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/task_useful_failure_by_model_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120/task_useful_failure_signatures.csv",
    "results/tables/openai_three_model_stress_v02_full120/token_burden_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120/token_burden_by_language.csv",
    "results/tables/openai_three_model_stress_v02_full120/token_burden_by_model.csv",
    "results/tables/openai_three_model_stress_v02_full120/token_burden_paired_effects_by_model.csv",
    "results/tables/openai_three_model_stress_v02_full120/token_burden_trajectory_metrics.csv",
    "results/tables/openai_three_model_stress_v02_full120/trajectory_metrics.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_audit_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_audit_by_model_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_audit_disagreements.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_audit_summary.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_agreement_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_agreement_by_model_condition.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_agreement_summary.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_component_agreement.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_component_disagreements.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_audit72/judge_pass_fail_disagreements.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_refresh_gpt55/judge_refresh_by_family.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_refresh_gpt55/judge_refresh_component_agreement.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_refresh_gpt55/judge_refresh_disagreements.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_refresh_gpt55/judge_refresh_pairwise_comparison.csv",
    "results/tables/openai_three_model_stress_v02_full120_judge_refresh_gpt55/judge_refresh_summary.csv",
    "results/tables/openai_three_model_stress_v02_repair_realism_editing_baseline24/repair_realism_by_model.csv",
    "results/tables/openai_three_model_stress_v02_repair_realism_editing_baseline24/repair_realism_disagreements.csv",
    "results/tables/openai_three_model_stress_v02_repair_realism_editing_baseline24/repair_realism_paired_effects.csv",
    "results/tables/openai_three_model_stress_v02_repair_realism_editing_baseline24/repair_realism_summary.csv",
    "results/tables/openai_three_model_stress_v02_new24/metrics_summary.csv",
    "scripts/analyze_benchmark_quality.py",
    "scripts/analyze_component_breakdown.py",
    "scripts/analyze_coverage_expansion_v03.py",
    "scripts/analyze_coverage_native_review_adjudication.py",
    "scripts/analyze_coverage_native_review_design_v03.py",
    "scripts/analyze_coverage_pilot_v03.py",
    "scripts/analyze_coverage_smoke_v03.py",
    "scripts/analyze_completed_label_claim_gates.py",
    "scripts/analyze_current_model_case_studies.py",
    "scripts/analyze_current_model_error_analysis.py",
    "scripts/analyze_current_model_heterogeneity.py",
    "scripts/analyze_current_model_regression_risk.py",
    "scripts/analyze_current_model_refresh.py",
    "scripts/analyze_current_model_uncertainty.py",
    "scripts/analyze_current_model_scorer_sensitivity.py",
    "scripts/analyze_current_prompt_mechanism.py",
    "scripts/analyze_prompt_family_scorecard.py",
    "scripts/analyze_all_model_paired_significance.py",
    "scripts/analyze_all_model_uncertainty.py",
    "scripts/analyze_contract_benefit_decomposition.py",
    "scripts/analyze_efficiency_tradeoff.py",
    "scripts/analyze_followup_plan_readiness.py",
    "scripts/analyze_failure_modes.py",
    "scripts/analyze_generation_progress_probe.py",
    "scripts/analyze_discovery_cues.py",
    "scripts/analyze_human_audit_design.py",
    "scripts/analyze_human_audit_adjudication.py",
    "scripts/analyze_human_audit_acceptance_rules.py",
    "scripts/analyze_human_audit_threshold_rationale.py",
    "scripts/analyze_item_consistency.py",
    "scripts/analyze_judge_agreement.py",
    "scripts/analyze_judge_refresh.py",
    "scripts/analyze_label_collection_launch_pack.py",
    "scripts/analyze_label_collection_dispatch.py",
    "scripts/analyze_language_slices.py",
    "scripts/analyze_prompt_ablation.py",
    "scripts/analyze_prompt_control.py",
    "scripts/analyze_repair_realism.py",
    "scripts/analyze_repair_dynamics.py",
    "scripts/analyze_scorer_ablation.py",
    "scripts/analyze_task_useful_failures.py",
    "scripts/analyze_token_burden.py",
    "scripts/build_coverage_pilot_v03_outputs.py",
    "scripts/build_full_v02_scores.py",
    "scripts/build_full_v02_prompt_control_scores.py",
    "scripts/build_label_collection_bundles.py",
    "scripts/build_error_atlas.py",
    "scripts/compute_metrics.py",
    "scripts/discover_repair_cues.py",
    "scripts/finalize_coverage_native_review_adjudication.py",
    "scripts/finalize_human_audit_adjudication.py",
    "scripts/generate_benchmark.py",
    "scripts/generate_coverage_expansion_v03.py",
    "scripts/generate_stress_benchmark.py",
    "scripts/generate_stress_benchmark_v02.py",
    "scripts/judge_outputs.py",
    "scripts/lint_claim_boundaries.py",
    "scripts/make_artifact_manifest.py",
    "scripts/make_coverage_native_review_packet_v03.py",
    "scripts/make_coverage_native_review_sheets_v03.py",
    "scripts/make_figures.py",
    "scripts/make_human_audit_packet.py",
    "scripts/make_human_audit_review_sheets.py",
    "scripts/merge_review_exports.py",
    "scripts/paired_effects.py",
    "scripts/paired_significance.py",
    "scripts/run_models.py",
    "scripts/run_repair_prompt_variants.py",
    "scripts/run_submission_checks.py",
    "scripts/score_auto.py",
    "scripts/summarize_human_audit.py",
    "scripts/summarize_experiment_ledger.py",
    "scripts/summarize_coverage_native_review_v03.py",
    "scripts/summarize_judge_audit.py",
    "scripts/test_coverage_native_review_adjudication.py",
    "scripts/test_coverage_native_review_completion.py",
    "scripts/test_completed_label_claim_gates.py",
    "scripts/test_human_audit_adjudication.py",
    "scripts/test_score_auto.py",
    "scripts/test_human_audit_completion.py",
    "scripts/test_merge_review_exports.py",
    "scripts/validate_completed_coverage_native_review_v03.py",
    "scripts/validate_completed_label_claim_gates.py",
    "scripts/validate_completed_human_audit.py",
    "scripts/validate_label_collection_bundles.py",
    "scripts/validate_current_model_human_audit_packet.py",
    "scripts/validate_current_model_case_studies.py",
    "scripts/validate_current_model_error_analysis.py",
    "scripts/validate_current_model_heterogeneity.py",
    "scripts/validate_current_model_regression_risk.py",
    "scripts/validate_current_model_refresh.py",
    "scripts/validate_current_model_uncertainty.py",
    "scripts/validate_current_model_scorer_sensitivity.py",
    "scripts/validate_current_prompt_mechanism.py",
    "scripts/validate_prompt_family_scorecard.py",
    "scripts/validate_all_model_paired_significance.py",
    "scripts/validate_all_model_uncertainty.py",
    "scripts/validate_contract_benefit_decomposition.py",
    "scripts/validate_efficiency_tradeoff.py",
    "scripts/validate_followup_plan_readiness.py",
    "scripts/validate_generation_progress_probe.py",
    "scripts/validate_coverage_expansion_v03.py",
    "scripts/validate_coverage_native_review_packet_v03.py",
    "scripts/validate_coverage_native_review_sheets_v03.py",
    "scripts/validate_coverage_pilot_v03.py",
    "scripts/validate_coverage_smoke_v03.py",
    "scripts/validate_followup_probe.py",
    "scripts/validate_human_audit_packet.py",
    "scripts/validate_human_audit_review_sheets.py",
    "scripts/validate_human_audit_acceptance_rules.py",
    "scripts/validate_human_audit_threshold_rationale.py",
    "scripts/validate_judge_refresh.py",
    "scripts/validate_label_collection_launch_pack.py",
    "scripts/validate_label_collection_dispatch.py",
    "scripts/validate_paper_claims.py",
    "scripts/validate_repair_realism.py",
    "scripts/validate_qualitative_examples.py",
    "scripts/validate_release_docs.py",
    "scripts/validate_result_card.py",
    "scripts/validate_stress_benchmark.py",
]

REPRODUCTION_COMMANDS = [
    "conda run -n reprompt_tax python scripts/run_submission_checks.py",
    "conda run -n reprompt_tax python scripts/build_full_v02_scores.py",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_three_model_stress_v02_full120",
    "conda run -n reprompt_tax python scripts/build_full_v02_prompt_control_scores.py",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_nano_stress_v02_full120_generic_helpfulness_auto_scores.jsonl --out-dir results/tables/openai_nano_stress_v02_full120_generic_helpfulness",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.2.jsonl --outputs results/model_outputs/openai_nano_stress_v02_full120_content_preservation.jsonl --out results/scores/openai_nano_stress_v02_full120_content_preservation_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_nano_stress_v02_full120_content_preservation_auto_scores.jsonl --out-dir results/tables/openai_nano_stress_v02_full120_content_preservation",
    "conda run -n reprompt_tax python scripts/paired_effects.py --trajectory-metrics results/tables/openai_three_model_stress_v02_full120/trajectory_metrics.csv --out-dir results/tables/openai_three_model_stress_v02_full120",
    "conda run -n reprompt_tax python scripts/analyze_language_slices.py --trajectory-metrics results/tables/openai_three_model_stress_v02_full120/trajectory_metrics.csv --out-dir results/tables/openai_three_model_stress_v02_full120 --out-md paper/language_slice_analysis_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_repair_dynamics.py --trajectory-metrics results/tables/openai_three_model_stress_v02_full120/trajectory_metrics.csv --out-dir results/tables/openai_three_model_stress_v02_full120 --out-md paper/repair_dynamics_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_benchmark_quality.py --benchmark data/benchmark_stress_v0.2.jsonl --out-dir results/tables/benchmark_quality_v02 --out-md paper/benchmark_quality_audit_v02.md",
    "conda run -n reprompt_tax python scripts/generate_coverage_expansion_v03.py --out data/benchmark_stress_v0.3_expansion.jsonl",
    "conda run -n reprompt_tax python scripts/analyze_coverage_expansion_v03.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --out-dir results/tables/coverage_expansion_v03 --out-md paper/coverage_expansion_v03.md",
    "conda run -n reprompt_tax python scripts/validate_coverage_expansion_v03.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --tables-dir results/tables/coverage_expansion_v03 --report paper/coverage_expansion_v03.md",
    "conda run -n reprompt_tax python scripts/make_coverage_native_review_packet_v03.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --out-dir data/coverage_native_review_v03",
    "conda run -n reprompt_tax python scripts/validate_coverage_native_review_packet_v03.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --out-dir data/coverage_native_review_v03",
    "conda run -n reprompt_tax python scripts/make_coverage_native_review_sheets_v03.py --packet data/coverage_native_review_v03/coverage_native_review_packet_v03.csv --out-dir data/coverage_native_review_v03/review_sheets_v03",
    "conda run -n reprompt_tax python scripts/validate_coverage_native_review_sheets_v03.py --packet data/coverage_native_review_v03/coverage_native_review_packet_v03.csv --out-dir data/coverage_native_review_v03/review_sheets_v03",
    "conda run -n reprompt_tax python scripts/analyze_coverage_native_review_design_v03.py --packet data/coverage_native_review_v03/coverage_native_review_packet_v03.csv --out-dir results/tables/coverage_native_review_v03_design --out-md paper/coverage_native_review_design_v03.md",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --outputs results/model_outputs/openai_gpt54mini_stress_v03_smoke6.jsonl --out results/scores/openai_gpt54mini_stress_v03_smoke6_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt54mini_stress_v03_smoke6_auto_scores.jsonl --out-dir results/tables/openai_gpt54mini_stress_v03_smoke6",
    "conda run -n reprompt_tax python scripts/analyze_coverage_smoke_v03.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --scores results/scores/openai_gpt54mini_stress_v03_smoke6_auto_scores.jsonl --outputs results/model_outputs/openai_gpt54mini_stress_v03_smoke6.jsonl --out-dir results/tables/openai_gpt54mini_stress_v03_smoke6 --out-md paper/coverage_smoke_gpt54mini_v03.md",
    "conda run -n reprompt_tax python scripts/validate_coverage_smoke_v03.py --outputs results/model_outputs/openai_gpt54mini_stress_v03_smoke6.jsonl --scores results/scores/openai_gpt54mini_stress_v03_smoke6_auto_scores.jsonl --tables-dir results/tables/openai_gpt54mini_stress_v03_smoke6 --report paper/coverage_smoke_gpt54mini_v03.md",
    "conda run -n reprompt_tax python scripts/build_coverage_pilot_v03_outputs.py --smoke results/model_outputs/openai_gpt54mini_stress_v03_smoke6.jsonl --remaining results/model_outputs/openai_gpt54mini_stress_v03_pilot24_remaining18.jsonl --pilot-ids data/stress_v03_pilot24_ids.txt --out results/model_outputs/openai_gpt54mini_stress_v03_pilot24.jsonl",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --outputs results/model_outputs/openai_gpt54mini_stress_v03_pilot24.jsonl --out results/scores/openai_gpt54mini_stress_v03_pilot24_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt54mini_stress_v03_pilot24_auto_scores.jsonl --out-dir results/tables/openai_gpt54mini_stress_v03_pilot24",
    "conda run -n reprompt_tax python scripts/analyze_coverage_pilot_v03.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --scores results/scores/openai_gpt54mini_stress_v03_pilot24_auto_scores.jsonl --outputs results/model_outputs/openai_gpt54mini_stress_v03_pilot24.jsonl --out-dir results/tables/openai_gpt54mini_stress_v03_pilot24 --out-md paper/coverage_pilot_gpt54mini_v03.md",
    "conda run -n reprompt_tax python scripts/validate_coverage_pilot_v03.py --outputs results/model_outputs/openai_gpt54mini_stress_v03_pilot24.jsonl --scores results/scores/openai_gpt54mini_stress_v03_pilot24_auto_scores.jsonl --tables-dir results/tables/openai_gpt54mini_stress_v03_pilot24 --report paper/coverage_pilot_gpt54mini_v03.md",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --outputs results/model_outputs/openai_gpt55_stress_v03_smoke6.jsonl --out results/scores/openai_gpt55_stress_v03_smoke6_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt55_stress_v03_smoke6_auto_scores.jsonl --out-dir results/tables/openai_gpt55_stress_v03_smoke6",
    "conda run -n reprompt_tax python scripts/analyze_coverage_smoke_v03.py --benchmark data/benchmark_stress_v0.3_expansion.jsonl --scores results/scores/openai_gpt55_stress_v03_smoke6_auto_scores.jsonl --outputs results/model_outputs/openai_gpt55_stress_v03_smoke6.jsonl --out-dir results/tables/openai_gpt55_stress_v03_smoke6 --out-md paper/coverage_smoke_gpt55_v03.md",
    "conda run -n reprompt_tax python scripts/validate_coverage_smoke_v03.py --outputs results/model_outputs/openai_gpt55_stress_v03_smoke6.jsonl --scores results/scores/openai_gpt55_stress_v03_smoke6_auto_scores.jsonl --tables-dir results/tables/openai_gpt55_stress_v03_smoke6 --report paper/coverage_smoke_gpt55_v03.md --expected-model gpt-5.5 --expected-api-rows 12 --expected-input-tokens 1632 --expected-output-tokens 870 --expected-baseline-first-turn-passes 6 --expected-contract-first-turn-passes 6 --expected-first-turn-failure-count 0 --expected-successful-repair-rows 0 --expected-baseline-mean-rtt 0 --expected-contract-mean-rtt 0 --expected-es-ar-baseline-ftga 1 --expected-failure-item '' --expected-failure-types ''",
    "conda run -n reprompt_tax python scripts/analyze_token_burden.py --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_three_model_stress_v02_full120 --out-md paper/token_burden_analysis_v02_full120.md",
    "conda run -n reprompt_tax python scripts/summarize_experiment_ledger.py --out-dir results/tables/experiment_ledger_v02 --out-md paper/experiment_ledger_v02.md",
    "conda run -n reprompt_tax python scripts/analyze_failure_modes.py --tables-dir results/tables/openai_three_model_stress_v02_full120 --paper-out paper/failure_mode_analysis_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_item_consistency.py --trajectory-metrics results/tables/openai_three_model_stress_v02_full120/trajectory_metrics.csv --out-dir results/tables/openai_three_model_stress_v02_full120 --out-md paper/item_consistency_analysis_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_component_breakdown.py --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_three_model_stress_v02_full120 --out-md paper/component_breakdown_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_scorer_ablation.py --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_three_model_stress_v02_full120 --out-md paper/scorer_ablation_sensitivity_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_task_useful_failures.py --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_three_model_stress_v02_full120 --out-md paper/task_useful_failure_analysis_v02_full120.md --expected-first-turn-rows 720",
    "conda run -n reprompt_tax python scripts/analyze_prompt_control.py",
    "conda run -n reprompt_tax python scripts/analyze_prompt_ablation.py",
    "conda run -n reprompt_tax python scripts/build_error_atlas.py --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --trajectories results/tables/openai_three_model_stress_v02_full120/trajectory_metrics.csv --out-csv results/tables/openai_three_model_stress_v02_full120/first_turn_error_atlas.csv --out-md paper/error_atlas_v02_full120.md",
    "conda run -n reprompt_tax python scripts/paired_significance.py --trajectory-metrics results/tables/openai_three_model_stress_v02_full120/trajectory_metrics.csv --out-csv results/tables/openai_three_model_stress_v02_full120/paired_significance_by_model.csv --out-md paper/paired_significance_v02_full120.md",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.2.jsonl --outputs results/model_outputs/openai_gpt54mini_stress_v02_full120.jsonl --out results/scores/openai_gpt54mini_stress_v02_full120_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt54mini_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_gpt54mini_stress_v02_full120",
    "conda run -n reprompt_tax python scripts/paired_effects.py --trajectory-metrics results/tables/openai_gpt54mini_stress_v02_full120/trajectory_metrics.csv --out-dir results/tables/openai_gpt54mini_stress_v02_full120",
    "conda run -n reprompt_tax python scripts/paired_significance.py --trajectory-metrics results/tables/openai_gpt54mini_stress_v02_full120/trajectory_metrics.csv --out-csv results/tables/openai_gpt54mini_stress_v02_full120/paired_significance_by_model.csv --out-md paper/paired_significance_gpt54mini_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_task_useful_failures.py --scores results/scores/openai_gpt54mini_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_gpt54mini_stress_v02_full120 --out-md paper/task_useful_failure_analysis_gpt54mini_v02_full120.md --expected-first-turn-rows 240",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.2.jsonl --outputs results/model_outputs/openai_gpt54mini_stress_v02_full120_content_preservation.jsonl --out results/scores/openai_gpt54mini_stress_v02_full120_content_preservation_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt54mini_stress_v02_full120_content_preservation_auto_scores.jsonl --out-dir results/tables/openai_gpt54mini_stress_v02_full120_content_preservation",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.2.jsonl --outputs results/model_outputs/openai_gpt55_stress_v02_pilot40.jsonl --out results/scores/openai_gpt55_stress_v02_pilot40_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt55_stress_v02_pilot40_auto_scores.jsonl --out-dir results/tables/openai_gpt55_stress_v02_pilot40",
    "conda run -n reprompt_tax python scripts/paired_effects.py --trajectory-metrics results/tables/openai_gpt55_stress_v02_pilot40/trajectory_metrics.csv --out-dir results/tables/openai_gpt55_stress_v02_pilot40",
    "conda run -n reprompt_tax python scripts/paired_significance.py --trajectory-metrics results/tables/openai_gpt55_stress_v02_pilot40/trajectory_metrics.csv --out-csv results/tables/openai_gpt55_stress_v02_pilot40/paired_significance_by_model.csv --out-md paper/paired_significance_gpt55_v02_pilot40.md",
    "conda run -n reprompt_tax python scripts/analyze_task_useful_failures.py --scores results/scores/openai_gpt55_stress_v02_pilot40_auto_scores.jsonl --out-dir results/tables/openai_gpt55_stress_v02_pilot40 --out-md paper/task_useful_failure_analysis_gpt55_v02_pilot40.md --expected-first-turn-rows 80",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.2.jsonl --outputs results/model_outputs/openai_gpt55_stress_v02_full120.jsonl --out results/scores/openai_gpt55_stress_v02_full120_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt55_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_gpt55_stress_v02_full120",
    "conda run -n reprompt_tax python scripts/paired_effects.py --trajectory-metrics results/tables/openai_gpt55_stress_v02_full120/trajectory_metrics.csv --out-dir results/tables/openai_gpt55_stress_v02_full120",
    "conda run -n reprompt_tax python scripts/paired_significance.py --trajectory-metrics results/tables/openai_gpt55_stress_v02_full120/trajectory_metrics.csv --out-csv results/tables/openai_gpt55_stress_v02_full120/paired_significance_by_model.csv --out-md paper/paired_significance_gpt55_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_task_useful_failures.py --scores results/scores/openai_gpt55_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_gpt55_stress_v02_full120 --out-md paper/task_useful_failure_analysis_gpt55_v02_full120.md --expected-first-turn-rows 240",
    "conda run -n reprompt_tax python scripts/score_auto.py --benchmark data/benchmark_stress_v0.2.jsonl --outputs results/model_outputs/openai_gpt55_stress_v02_full120_content_preservation.jsonl --out results/scores/openai_gpt55_stress_v02_full120_content_preservation_auto_scores.jsonl",
    "conda run -n reprompt_tax python scripts/compute_metrics.py --scores results/scores/openai_gpt55_stress_v02_full120_content_preservation_auto_scores.jsonl --out-dir results/tables/openai_gpt55_stress_v02_full120_content_preservation",
    "conda run -n reprompt_tax python scripts/analyze_current_model_refresh.py",
    "conda run -n reprompt_tax python scripts/validate_current_model_refresh.py",
    "conda run -n reprompt_tax python scripts/analyze_current_model_uncertainty.py",
    "conda run -n reprompt_tax python scripts/validate_current_model_uncertainty.py",
    "conda run -n reprompt_tax python scripts/analyze_current_model_heterogeneity.py",
    "conda run -n reprompt_tax python scripts/validate_current_model_heterogeneity.py",
    "conda run -n reprompt_tax python scripts/analyze_current_model_regression_risk.py",
    "conda run -n reprompt_tax python scripts/validate_current_model_regression_risk.py",
    "conda run -n reprompt_tax python scripts/analyze_current_model_error_analysis.py",
    "conda run -n reprompt_tax python scripts/validate_current_model_error_analysis.py",
    "conda run -n reprompt_tax python scripts/analyze_current_model_case_studies.py",
    "conda run -n reprompt_tax python scripts/validate_current_model_case_studies.py",
    "conda run -n reprompt_tax python scripts/analyze_current_model_scorer_sensitivity.py",
    "conda run -n reprompt_tax python scripts/validate_current_model_scorer_sensitivity.py",
    "conda run -n reprompt_tax python scripts/analyze_generation_progress_probe.py",
    "conda run -n reprompt_tax python scripts/validate_generation_progress_probe.py",
    "conda run -n reprompt_tax python scripts/analyze_efficiency_tradeoff.py",
    "conda run -n reprompt_tax python scripts/validate_efficiency_tradeoff.py",
    "conda run -n reprompt_tax python scripts/analyze_followup_plan_readiness.py",
    "conda run -n reprompt_tax python scripts/validate_followup_plan_readiness.py",
    "conda run -n reprompt_tax python scripts/analyze_human_audit_acceptance_rules.py",
    "conda run -n reprompt_tax python scripts/validate_human_audit_acceptance_rules.py",
    "conda run -n reprompt_tax python scripts/analyze_human_audit_threshold_rationale.py",
    "conda run -n reprompt_tax python scripts/validate_human_audit_threshold_rationale.py",
    "conda run -n reprompt_tax python scripts/analyze_completed_label_claim_gates.py",
    "conda run -n reprompt_tax python scripts/validate_completed_label_claim_gates.py",
    "conda run -n reprompt_tax python scripts/analyze_label_collection_launch_pack.py",
    "conda run -n reprompt_tax python scripts/validate_label_collection_launch_pack.py",
    "conda run -n reprompt_tax python scripts/build_label_collection_bundles.py",
    "conda run -n reprompt_tax python scripts/validate_label_collection_bundles.py",
    "conda run -n reprompt_tax python scripts/analyze_label_collection_dispatch.py",
    "conda run -n reprompt_tax python scripts/validate_label_collection_dispatch.py",
    "conda run -n reprompt_tax python scripts/analyze_current_prompt_mechanism.py",
    "conda run -n reprompt_tax python scripts/validate_current_prompt_mechanism.py",
    "conda run -n reprompt_tax python scripts/analyze_prompt_family_scorecard.py",
    "conda run -n reprompt_tax python scripts/validate_prompt_family_scorecard.py",
    "conda run -n reprompt_tax python scripts/analyze_all_model_paired_significance.py",
    "conda run -n reprompt_tax python scripts/validate_all_model_paired_significance.py",
    "conda run -n reprompt_tax python scripts/analyze_all_model_uncertainty.py",
    "conda run -n reprompt_tax python scripts/validate_all_model_uncertainty.py",
    "conda run -n reprompt_tax python scripts/analyze_contract_benefit_decomposition.py",
    "conda run -n reprompt_tax python scripts/validate_contract_benefit_decomposition.py",
    "conda run -n reprompt_tax python scripts/analyze_judge_agreement.py --audit results/scores/openai_three_model_stress_v02_full120_judge_audit72.jsonl --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --out-dir results/tables/openai_three_model_stress_v02_full120_judge_audit72 --out-md paper/judge_agreement_analysis_v02_full120.md",
    "conda run -n reprompt_tax python scripts/analyze_judge_refresh.py",
    "conda run -n reprompt_tax python scripts/validate_judge_refresh.py",
    "conda run -n reprompt_tax python scripts/analyze_repair_realism.py",
    "conda run -n reprompt_tax python scripts/validate_repair_realism.py",
    "conda run -n reprompt_tax python scripts/make_figures.py --tables-dir results/tables/openai_three_model_stress_v02_full120 --extra-summary results/tables/openai_gpt54mini_stress_v02_full120/metrics_summary.csv --extra-summary results/tables/openai_gpt55_stress_v02_full120/metrics_summary.csv --extra-trajectories results/tables/openai_gpt54mini_stress_v02_full120/trajectory_metrics.csv --extra-trajectories results/tables/openai_gpt55_stress_v02_full120/trajectory_metrics.csv --out-dir results/figures/openai_three_model_stress_v02_full120",
    "conda run -n reprompt_tax python scripts/make_human_audit_packet.py --benchmark data/benchmark_stress_v0.2.jsonl --scores results/scores/openai_three_model_stress_v02_full120_auto_scores.jsonl --out-dir data/human_audit --packet-version v0.2 --seed 23",
    "conda run -n reprompt_tax python scripts/make_human_audit_review_sheets.py --packet data/human_audit/human_audit_packet_v0.2.csv --out-dir data/human_audit/review_sheets_v0.2 --packet-version v0.2",
    "conda run -n reprompt_tax python scripts/validate_human_audit_review_sheets.py --packet data/human_audit/human_audit_packet_v0.2.csv --out-dir data/human_audit/review_sheets_v0.2 --packet-version v0.2",
    "conda run -n reprompt_tax python scripts/analyze_human_audit_design.py --packet data/human_audit/human_audit_packet_v0.2.csv --answer-key data/human_audit/human_audit_answer_key_v0.2.csv --out-dir results/tables/human_audit_v0.2_design --out-md paper/human_audit_design_audit_v02.md",
    "conda run -n reprompt_tax python scripts/make_human_audit_packet.py --benchmark data/benchmark_stress_v0.2.jsonl --scores results/scores/openai_gpt54mini_stress_v02_full120_auto_scores.jsonl results/scores/openai_gpt55_stress_v02_full120_auto_scores.jsonl --out-dir data/current_model_human_audit --packet-version v0.2_current_gpt5 --seed 29 --prefer-failures",
    "conda run -n reprompt_tax python scripts/validate_human_audit_packet.py --out-dir data/current_model_human_audit --packet-version v0.2_current_gpt5 --expected-models gpt-5.4-mini,gpt-5.5",
    "conda run -n reprompt_tax python scripts/make_human_audit_review_sheets.py --packet data/current_model_human_audit/human_audit_packet_v0.2_current_gpt5.csv --out-dir data/current_model_human_audit/review_sheets_v0.2_current_gpt5 --packet-version v0.2_current_gpt5",
    "conda run -n reprompt_tax python scripts/validate_human_audit_review_sheets.py --packet data/current_model_human_audit/human_audit_packet_v0.2_current_gpt5.csv --out-dir data/current_model_human_audit/review_sheets_v0.2_current_gpt5 --packet-version v0.2_current_gpt5",
    "conda run -n reprompt_tax python scripts/analyze_human_audit_design.py --packet data/current_model_human_audit/human_audit_packet_v0.2_current_gpt5.csv --answer-key data/current_model_human_audit/human_audit_answer_key_v0.2_current_gpt5.csv --out-dir results/tables/current_model_human_audit_v02_design --out-md paper/current_model_human_audit_design_v02.md --expected-models gpt-5.4-mini,gpt-5.5 --title 'Current-Model Human Audit Design Audit'",
    "conda run -n reprompt_tax python scripts/validate_current_model_human_audit_packet.py",
    "conda run -n reprompt_tax python scripts/test_coverage_native_review_completion.py",
    "conda run -n reprompt_tax python scripts/test_coverage_native_review_adjudication.py",
    "conda run -n reprompt_tax python scripts/test_human_audit_adjudication.py",
    "conda run -n reprompt_tax python scripts/test_merge_review_exports.py",
    "conda run -n reprompt_tax python scripts/test_completed_label_claim_gates.py",
    "conda run -n reprompt_tax python scripts/test_score_auto.py",
    "conda run -n reprompt_tax python scripts/lint_claim_boundaries.py",
    "conda run -n reprompt_tax python scripts/validate_result_card.py",
    "cd paper && latexmk -pdf -interaction=nonstopmode main.tex",
    "conda run -n reprompt_tax python scripts/validate_paper_claims.py",
    "conda run -n reprompt_tax python scripts/validate_qualitative_examples.py",
    "conda run -n reprompt_tax python scripts/validate_followup_probe.py",
    "conda run -n reprompt_tax python scripts/validate_human_audit_packet.py",
    "conda run -n reprompt_tax python scripts/validate_stress_benchmark.py --benchmark data/benchmark_stress_v0.2.jsonl --expected-per-cell 10",
    "conda run -n reprompt_tax python scripts/discover_repair_cues.py --dataset allenai/WildChat --split train --max-conversations 20000 --out-dir results/discovery/wildchat_20k_repair_cues",
    "conda run -n reprompt_tax python scripts/analyze_discovery_cues.py --summary results/discovery/wildchat_20k_repair_cues/summary.json --metadata results/discovery/wildchat_20k_repair_cues/hit_metadata_hashed.csv --out-dir results/discovery/wildchat_20k_repair_cues --out-md paper/discovery_cue_analysis.md",
    "rg -n \"Warning|undefined|Overfull|Underfull|Error\" paper/main.log",
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def line_count(path: Path) -> int | str:
    try:
        return len(path.read_text(encoding="utf-8").splitlines())
    except UnicodeDecodeError:
        return ""


def artifact_entry(root: Path, rel_path: str) -> dict[str, Any]:
    path = root / rel_path
    if not path.exists():
        raise FileNotFoundError(f"missing artifact: {rel_path}")
    return {
        "path": rel_path,
        "bytes": path.stat().st_size,
        "lines": line_count(path),
        "sha256": sha256(path),
    }


def build_manifest(root: Path) -> dict[str, Any]:
    return {
        "schema_version": "reprompt-tax-artifact-manifest-v1",
        "notes": [
            "Deterministic manifest for paper-facing artifacts only.",
            "API keys, raw external logs, caches, and TeX build intermediates are intentionally excluded.",
            "Run scripts/make_artifact_manifest.py after regenerating artifacts.",
        ],
        "reproduction_commands": REPRODUCTION_COMMANDS,
        "artifacts": [artifact_entry(root, rel_path) for rel_path in sorted(ARTIFACT_PATHS)],
    }


def write_markdown(path: Path, manifest: dict[str, Any]) -> None:
    lines = [
        "# RePromptTax Artifact Manifest",
        "",
        f"Schema: `{manifest['schema_version']}`",
        "",
        "## Notes",
        "",
    ]
    for note in manifest["notes"]:
        lines.append(f"- {note}")
    lines.extend(["", "## Reproduction Commands", ""])
    for command in manifest["reproduction_commands"]:
        lines.append(f"- `{command}`")
    lines.extend(["", "## Artifacts", "", "| Path | Bytes | Lines | SHA-256 |", "|---|---:|---:|---|"])
    for artifact in manifest["artifacts"]:
        lines.append(
            "| "
            f"`{artifact['path']}` | "
            f"{artifact['bytes']} | "
            f"{artifact['lines']} | "
            f"`{artifact['sha256']}` |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def check_manifest(root: Path, json_path: Path) -> None:
    if not json_path.exists():
        raise AssertionError(f"missing artifact manifest {json_path}")
    expected = json.loads(json_path.read_text(encoding="utf-8"))
    actual = build_manifest(root)
    if actual != expected:
        expected_by_path = {row["path"]: row for row in expected.get("artifacts", [])}
        actual_by_path = {row["path"]: row for row in actual.get("artifacts", [])}
        missing = sorted(set(actual_by_path) - set(expected_by_path))
        extra = sorted(set(expected_by_path) - set(actual_by_path))
        changed = sorted(
            path
            for path in set(actual_by_path).intersection(expected_by_path)
            if actual_by_path[path] != expected_by_path[path]
        )
        raise AssertionError(
            "artifact manifest is stale or inconsistent: "
            f"missing={missing}, extra={extra}, changed={changed[:10]}"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--out-json", type=Path, default=Path("paper/artifact_manifest.json"))
    parser.add_argument("--out-md", type=Path, default=Path("paper/artifact_manifest.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    out_json = args.out_json if args.out_json.is_absolute() else root / args.out_json
    out_md = args.out_md if args.out_md.is_absolute() else root / args.out_md
    if args.check:
        check_manifest(root, out_json)
        print(f"artifact manifest validation passed for {out_json}")
        return

    manifest = build_manifest(root)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(out_md, manifest)
    print(f"wrote artifact manifest to {out_json} and {out_md}")


if __name__ == "__main__":
    main()
